version: '3.3'
volumes:
  db-data:

services:
  db:
    image: postgres:14.4-bullseye
    container_name: postgres_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /tmp/postgresdev/db/data
    volumes:
      - db-data:/tmp/postgresdev/db/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "512m"